[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  path = "/verify"
  function = "verify"

[[edge_functions]]
  path = "/config"
  function = "verify"

[[edge_functions]]
  path = "/create-payment-intent"
  function = "verify"
